llm_config:
  base_url: https://api.deepseek.com/
  api_key: sk-6ea98f9850914ef1a0e728e0b0a145d5
  model_name: deepseek-v4-flash
  temperature: 0.7
  max_tokens: 8192
agent_config:
  max_iterations: 100
  max_retries: 3
  max_search_results: 10
mcp_config:
  mcpServers:
    amap-maps-streamableHTTP:
      transport: streamable_http
      enabled: true
      description: null
      env: null
      command: null
      args: null
      url: https://mcp.amap.com/mcp?key=a14b013a9c2dade51642e9d1b025757d
      headers: null
a2a_config:
  a2a_servers: [ ]
